ALTER TABLE public.companies
ADD COLUMN IF NOT EXISTS invoice_prefix TEXT DEFAULT 'INV-',
ADD COLUMN IF NOT EXISTS quotation_prefix TEXT DEFAULT 'QT-',
ADD COLUMN IF NOT EXISTS order_prefix TEXT DEFAULT 'SO-',
ADD COLUMN IF NOT EXISTS shipment_prefix TEXT DEFAULT 'SH-';
