ALTER TABLE public.system_settings 
ADD COLUMN IF NOT EXISTS morning_login_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS morning_login_time TEXT DEFAULT '08:00:00',
ADD COLUMN IF NOT EXISTS lunch_break_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS lunch_break_start TEXT DEFAULT '13:00:00',
ADD COLUMN IF NOT EXISTS lunch_break_end TEXT DEFAULT '13:45:00',
ADD COLUMN IF NOT EXISTS idle_logout_enabled BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS idle_minutes INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS idle_seconds INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS evening_logout_enabled BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS eod_time TEXT DEFAULT '17:45:00',
ADD COLUMN IF NOT EXISTS eod_hour INTEGER DEFAULT 17,
ADD COLUMN IF NOT EXISTS eod_minute INTEGER DEFAULT 45;
